#!/bin/bash
# arquivo com as principais funções

interface(){
	clear
opcao = 6
while [ "$opcao" != "6" ]
do	
	echo "------------------"
	echo "INTERFACE:"
	echo "1 - Gerenciar Usuários"
	echo "2 - ..."
	echo "3 - ..."
	echo "4 - ..."
	echo "5 - ..."
	echo "6 - exit"
	echo "O que deseja fazer: "
	read opcao
	clear
	case $opcao in
		1) gerenciarUsuario	;;
		2) echo "2";;
		3) echo "3";;
		4) echo "4";;
		5) echo "5";;
		6) echo exit;;
		*) echo "opção invalida";;
	esac	
done
}