#!/bin/bash
# arquivo com as principais funções
interface(){
	clear
	opcao = 6
	while [ "$opcao" != "0" ]
	do	
		echo "------------------"
		echo "INTERFACE:"
		echo "1 - Gerenciar Usuários"
		echo "2 - Informações do Sistema"
		echo "3 - Diagnóstico de Rede"		
		echo "0 - Sair"
		echo "O que deseja fazer: "
		read opcao
		clear
		case $opcao in
			1) gerenciarUsuario	;;
			2) info 			;;
			3) diagnostico 		;;			
			0) echo "sair"      ;;
			*) echo "opção invalida";;
		esac	
	done
}