#!/bin/bash


#exemplo de entrar: ./argumento 10 20
echo "O nome deste script é: $0"
echo "Recebidos: $# argumentos: $*"
echo "O primeiro argumento recebido foi: $1"
echo "O segundo argumento recebido foi: $2"
